### ISSUE TITLE
DTOs missing model columns and relationships

### ISSUE THREAD

**Issue by EmilienBilly** [adocasts/package-dto#3]
## Description

Some model columns and relationships are missing from the generated DTO.

I tried both commands : `node ace make:dto dto_name` and `node ace generate:dtos`

## Example

Missing columns : 

### Model

```ts
import { BaseModel, column } from '@adonisjs/lucid/orm'

export default class Contact extends BaseModel {
  @column({ isPrimary: true })
  declare id: number

  @column()
  declare firstname: string

  @column()
  declare lastname: string

  @column()
  declare email: string | null
}
```

### Generated DTO

```ts
import { BaseModelDto } from '@adocasts.com/dto/base'
import Profile from '#models/profile'

export default class ProfileDto extends BaseModelDto {
  declare id: number
  declare name: string

  constructor(profile?: Profile) {
    super()

    if (!profile) return
    this.id = profile.id
    this.name = profile.name
  }
}
```

Missing relationships : 

### Model

```ts
import { BaseModel, column, hasMany } from '@adonisjs/lucid/orm'
import type { HasMany } from '@adonisjs/lucid/types/relations'
import Task from '#models/task'

export default class List extends BaseModel {
  static table = 'task_lists'
  @column({ isPrimary: true })
  declare id: number

  @column()
  declare title: string

  @column()
  declare boardId: number

  @hasMany(() => Task)
  declare tasks: HasMany<typeof Task>
}
```

### Generated DTO

```ts
import { BaseModelDto } from '@adocasts.com/dto/base'
import List from '#models/list'

export default class ListDto extends BaseModelDto {
  declare id: number
  declare title: string
  declare boardId: number

  constructor(list?: List) {
    super()

    if (!list) return
    this.id = list.id
    this.title = list.title
    this.boardId = list.boardId
  }
}
```

**Comment by tomgobich** [comment]
Thank you for reporting this Emilien!! This should now be fixed up, there was an issue where the last line inside the Model's class was getting omitted. 

I also added an exclusion for `static` properties as when I tested your provided `List` model from above, the `table` property got ported over into the DTO, which it shouldn't have.

Related releases are:
- v0.0.8 - [Fixed Issue Where Last Line of the Model's Class Is Omitted](https://github.com/adocasts/package-dto/releases/tag/v0.0.8)
- v0.0.9 - [Omit Static Properties from Model in Generated DTO](https://github.com/adocasts/package-dto/releases/tag/v0.0.9)

**Comment by EmilienBilly** [comment]
Working fine, thanks a lot Tom !

**Comment by tomgobich** [comment]
Awesome to hear, anytime Emilien!!
